# Generated by Django 5.2.17 on 2026-08-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_clientcompany"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_version", models.PositiveIntegerField(default=1)),
                ("temporary_intake_days", models.PositiveIntegerField(default=7)),
                ("completed_job_days", models.PositiveIntegerField(default=90)),
                ("uncommitted_workflow_days", models.PositiveIntegerField(default=180)),
                ("metadata_days", models.PositiveIntegerField(default=365)),
                ("organization_recovery_days", models.PositiveIntegerField(default=30)),
                ("legal_hold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RetentionException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("temporary_intake", "Temporary intake"),
                            ("completed_jobs", "Completed jobs"),
                            ("match_runs", "Obsolete shortlist bundles"),
                            ("outreach", "Abandoned outreach chains"),
                            ("metadata", "Usage and audit metadata"),
                            ("organization", "Organization deletion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("reason", models.CharField(max_length=500)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("scope", "object_id", "id"),
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="deletion_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_organization_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="purge_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("deletion_requested_at__isnull", True),
                        ("purge_after__isnull", True),
                    ),
                    models.Q(
                        ("deletion_requested_at__isnull", False),
                        ("is_active", False),
                        ("purge_after__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="organization_deletion_state_consistent",
            ),
        ),
        migrations.AddField(
            model_name="organizationretentionpolicy",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retention_policy",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationretentionpolicy",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_organization_retention_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="retentionexception",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_retention_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="retentionexception",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retention_exceptions",
                to="organizations.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationretentionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_version__gte", 1)),
                name="retention_policy_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationretentionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("temporary_intake_days__gte", 1),
                    ("temporary_intake_days__lte", 3650),
                    ("completed_job_days__gte", 1),
                    ("completed_job_days__lte", 3650),
                    ("uncommitted_workflow_days__gte", 1),
                    ("uncommitted_workflow_days__lte", 3650),
                    ("metadata_days__gte", 1),
                    ("metadata_days__lte", 3650),
                    ("organization_recovery_days__gte", 1),
                    ("organization_recovery_days__lte", 365),
                ),
                name="retention_policy_days_bounded",
            ),
        ),
        migrations.AddIndex(
            model_name="retentionexception",
            index=models.Index(
                fields=["organization", "scope", "is_active"],
                name="retention_exc_org_scope_idx",
            ),
        ),
    ]
