# Generated by Django 5.2.17 on 2026-09-22 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0003_organizationretentionpolicy_retentionexception_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationretentionpolicy",
            name="vacancy_candidate_lawful_basis",
            field=models.CharField(
                choices=[
                    ("not_recorded", "Not configured"),
                    ("consent", "Consent"),
                    ("contract", "Application or contract steps"),
                    ("legitimate_interests", "Legitimate interests"),
                    ("legal_obligation", "Legal obligation"),
                    ("other", "Other organization-approved reason"),
                ],
                default="not_recorded",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationretentionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "vacancy_candidate_lawful_basis__in",
                        [
                            "not_recorded",
                            "consent",
                            "contract",
                            "legitimate_interests",
                            "legal_obligation",
                            "other",
                        ],
                    )
                ),
                name="retention_policy_candidate_basis_valid",
            ),
        ),
    ]
