# Generated by Django 5.2.17 on 2026-08-14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matching", "0007_reviewdecision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("schema_version", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(5000)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_outreach_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_drafts",
                        to="matching.reviewdecision",
                    ),
                ),
                (
                    "shortlist_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_drafts",
                        to="matching.shortlistentry",
                    ),
                ),
            ],
            options={"ordering": ("-version", "-created_at", "id")},
        ),
        migrations.AddConstraint(
            model_name="outreachdraft",
            constraint=models.UniqueConstraint(
                fields=("shortlist_entry", "version"),
                name="unique_outreach_draft_version_per_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="outreachdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="outreach_draft_version_positive",
            ),
        ),
    ]
