# Generated by Django 5.2.17 on 2026-08-14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0007_reviewdecision"),
        ("outreach", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachDraftAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("copy", "Copy"), ("export", "Export")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="OutreachDraftApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(2000)]
                    ),
                ),
                ("contact_permission_confirmed", models.BooleanField()),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-approved_at", "-id")},
        ),
        migrations.AddField(
            model_name="outreachdraft",
            name="creation_method",
            field=models.CharField(
                choices=[
                    ("ai_generated", "AI generated"),
                    ("recruiter_edited", "Recruiter edited"),
                ],
                default="ai_generated",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="outreachdraft",
            name="parent_draft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="outreach.outreachdraft",
            ),
        ),
        migrations.AddConstraint(
            model_name="outreachdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("creation_method__in", ["ai_generated", "recruiter_edited"])
                ),
                name="outreach_draft_valid_creation_method",
            ),
        ),
        migrations.AddField(
            model_name="outreachdraftaction",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outreach_draft_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outreachdraftaction",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_actions",
                to="outreach.outreachdraft",
            ),
        ),
        migrations.AddField(
            model_name="outreachdraftapproval",
            name="approved_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_outreach_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outreachdraftapproval",
            name="draft",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="final_approval",
                to="outreach.outreachdraft",
            ),
        ),
        migrations.AddConstraint(
            model_name="outreachdraftaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("action_type__in", ["copy", "export"])),
                name="outreach_action_valid_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="outreachdraftapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(("contact_permission_confirmed", True)),
                name="outreach_approval_confirms_contact_permission",
            ),
        ),
    ]
