# Generated by Django 5.2.17 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_platform_owner",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Can provision organizations and manage their administrator "
                    "memberships without receiving organization data access."
                ),
            ),
        ),
    ]
