# Generated by Django 5.2.17 on 2026-08-10 14:46

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import candidates.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_clientcompany"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("deletion_requested", "Deletion requested"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("retention_until", models.DateField(blank=True, null=True)),
                ("deletion_requested_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("full_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CandidateSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual_entry", "Manual entry"),
                            ("csv_import", "CSV import"),
                            ("document_upload", "Document upload"),
                            ("ats_import", "ATS import"),
                            ("referral", "Referral"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_name", models.CharField(max_length=200)),
                ("source_reference", models.CharField(blank=True, max_length=500)),
                ("obtained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lawful_basis",
                    models.CharField(
                        choices=[
                            ("not_recorded", "Not recorded"),
                            ("consent", "Consent"),
                            ("contract", "Contract"),
                            ("legitimate_interests", "Legitimate interests"),
                            ("legal_obligation", "Legal obligation"),
                            ("other", "Other"),
                        ],
                        default="not_recorded",
                        max_length=30,
                    ),
                ),
                (
                    "contact_permission",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("permitted", "Permitted"),
                            ("restricted", "Restricted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("consent_updated_at", models.DateTimeField(blank=True, null=True)),
                ("permission_notes", models.TextField(blank=True)),
                ("retention_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_candidate_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CandidateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("cv", "CV or resume"),
                            ("cover_letter", "Cover letter"),
                            ("portfolio", "Portfolio"),
                            ("other", "Other"),
                        ],
                        default="cv",
                        max_length=30,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=candidates.models.candidate_document_upload_to,
                    ),
                ),
                (
                    "storage_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="SHA-256 must contain 64 lowercase hexadecimal characters.",
                                regex="\\A[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("retention_until", models.DateField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_candidate_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="candidates.candidatesource",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["organization", "status"], name="candidate_org_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["active", "inactive", "deletion_requested", "deleted"],
                    )
                ),
                name="candidate_has_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deletion_requested"), _negated=True),
                    ("deletion_requested_at__isnull", False),
                    _connector="OR",
                ),
                name="candidate_deletion_request_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deleted"), _negated=True),
                    ("deleted_at__isnull", False),
                    _connector="OR",
                ),
                name="deleted_candidate_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatesource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_type__in",
                        [
                            "manual_entry",
                            "csv_import",
                            "document_upload",
                            "ats_import",
                            "referral",
                            "other",
                        ],
                    )
                ),
                name="candidate_source_has_valid_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatesource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "lawful_basis__in",
                        [
                            "not_recorded",
                            "consent",
                            "contract",
                            "legitimate_interests",
                            "legal_obligation",
                            "other",
                        ],
                    )
                ),
                name="candidate_source_has_valid_lawful_basis",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatesource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "contact_permission__in",
                        ["unknown", "permitted", "restricted", "withdrawn"],
                    )
                ),
                name="candidate_source_has_valid_contact_permission",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("document_type__in", ["cv", "cover_letter", "portfolio", "other"])
                ),
                name="candidate_document_has_valid_type",
            ),
        ),
    ]
