# Generated by Django 5.2.17 on 2026-08-10 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatedocument",
            name="source",
        ),
        migrations.AddField(
            model_name="candidatesource",
            name="consent_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("not_required", "Not required"),
                    ("granted", "Granted"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatesource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "consent_status__in",
                        ["unknown", "not_required", "granted", "withdrawn"],
                    )
                ),
                name="candidate_source_has_valid_consent_status",
            ),
        ),
    ]
