# Generated by Django 5.2.17 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0002_remove_candidatedocument_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatedocument",
            name="extracted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidatedocument",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidatedocument",
            name="extraction_error_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="candidatedocument",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_status__in", ["pending", "succeeded", "failed"])
                ),
                name="candidate_document_has_valid_extraction_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_status", "succeeded"),
                    _negated=True,
                )
                | (
                    ~models.Q(("extracted_text", ""))
                    & models.Q(("extracted_at__isnull", False))
                    & models.Q(("extraction_error_code", ""))
                ),
                name="candidate_document_success_has_text",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_status", "failed"),
                    _negated=True,
                )
                | (
                    models.Q(("extracted_text", ""))
                    & models.Q(("extracted_at__isnull", False))
                    & ~models.Q(("extraction_error_code", ""))
                ),
                name="candidate_document_failure_has_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_status", "pending"),
                    _negated=True,
                )
                | (
                    models.Q(("extracted_text", ""))
                    & models.Q(("extracted_at__isnull", True))
                    & models.Q(("extraction_error_code", ""))
                ),
                name="candidate_document_pending_is_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="candidatedocument",
            index=models.Index(
                fields=["sha256"],
                name="candidate_doc_sha256_idx",
            ),
        ),
    ]
