# Generated by Django 5.2.17 on 2026-08-12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_candidatedocument_extraction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "schema_version",
                    models.CharField(
                        default="candidate_profile.v1",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("confirmed", "Confirmed")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "source_document_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "SHA-256 must contain 64 lowercase hexadecimal "
                                    "characters."
                                ),
                                regex="\\A[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "source_text_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "SHA-256 must contain 64 lowercase hexadecimal "
                                    "characters."
                                ),
                                regex="\\A[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("relevant_experience_summary", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("employment_history", models.JSONField(blank=True, default=list)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "work_mode_preference",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("on_site", "On site"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                            ("flexible", "Flexible"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("education", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                (
                    "employment_type_preferences",
                    models.JSONField(blank=True, default=list),
                ),
                ("availability", models.CharField(blank=True, max_length=300)),
                ("fact_evidence", models.JSONField(blank=True, default=dict)),
                ("ambiguities", models.JSONField(blank=True, default=list)),
                (
                    "excluded_sensitive_content_detected",
                    models.BooleanField(default=False),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_versions",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_candidate_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_candidate_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_versions",
                        to="candidates.candidatedocument",
                    ),
                ),
            ],
            options={
                "ordering": ("-version", "-created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate", "version"),
                        name="unique_candidate_profile_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="candidate_profile_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["draft", "confirmed"])),
                        name="candidate_profile_valid_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "work_mode_preference__in",
                                [
                                    "unknown",
                                    "on_site",
                                    "hybrid",
                                    "remote",
                                    "flexible",
                                ],
                            )
                        ),
                        name="candidate_profile_valid_work_mode",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("confirmed_at__isnull", True),
                                ("confirmed_by__isnull", True),
                                ("status", "draft"),
                            ),
                            models.Q(
                                ("confirmed_at__isnull", False),
                                ("confirmed_by__isnull", False),
                                ("status", "confirmed"),
                            ),
                            _connector="OR",
                        ),
                        name="candidate_profile_confirmation_consistent",
                    ),
                ],
            },
        ),
    ]
