# Generated by Django 5.2.17 on 2026-08-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0004_candidateprofile"),
        ("organizations", "0002_clientcompany"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="deletion_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_candidate_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="status_before_deletion_request",
            field=models.CharField(
                blank=True,
                choices=[("active", "Active"), ("inactive", "Inactive")],
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deletion_requested"), _negated=True),
                    (
                        "status_before_deletion_request__in",
                        ["active", "inactive"],
                    ),
                    _connector="OR",
                ),
                name="candidate_deletion_request_has_prior_status",
            ),
        ),
    ]
