# Generated by Django 5.2.17 on 2026-08-17 15:51

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import candidates.models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0005_candidate_deletion_requested_by_and_more"),
        ("organizations", "0002_clientcompany"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateIntakeBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=200)),
                (
                    "lawful_basis",
                    models.CharField(
                        choices=[
                            ("not_recorded", "Not recorded"),
                            ("consent", "Consent"),
                            ("contract", "Contract"),
                            ("legitimate_interests", "Legitimate interests"),
                            ("legal_obligation", "Legal obligation"),
                            ("other", "Other"),
                        ],
                        default="not_recorded",
                        max_length=30,
                    ),
                ),
                (
                    "consent_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("not_required", "Not required"),
                            ("granted", "Granted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "contact_permission",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("permitted", "Permitted"),
                            ("restricted", "Restricted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("permission_notes", models.TextField(blank=True)),
                ("candidate_retention_until", models.DateField(blank=True, null=True)),
                ("source_retention_until", models.DateField(blank=True, null=True)),
                ("document_retention_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("completed", "Completed"),
                            ("discarded", "Discarded"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_candidate_intake_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_intake_batches",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CandidateIntakeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("created", "Candidate created"),
                            ("skipped", "Discarded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to=candidates.models.candidate_intake_upload_to,
                    ),
                ),
                (
                    "storage_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="SHA-256 must contain 64 lowercase hexadecimal characters.",
                                regex="\\A[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("proposed_full_name", models.CharField(blank=True, max_length=200)),
                ("proposed_email", models.EmailField(blank=True, max_length=254)),
                ("proposed_phone", models.CharField(blank=True, max_length=50)),
                ("proposed_location", models.CharField(blank=True, max_length=200)),
                (
                    "proposed_source_reference",
                    models.CharField(blank=True, max_length=500),
                ),
                ("review_flags", models.JSONField(blank=True, default=list)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="candidates.candidateintakebatch",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_items",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_candidate_intake_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_candidate_intake_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddIndex(
            model_name="candidateintakebatch",
            index=models.Index(
                fields=["organization", "status"], name="cand_intake_org_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateintakebatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "completed", "discarded"])),
                name="candidate_intake_batch_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateintakebatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "lawful_basis__in",
                        [
                            "not_recorded",
                            "consent",
                            "contract",
                            "legitimate_interests",
                            "legal_obligation",
                            "other",
                        ],
                    )
                ),
                name="candidate_intake_batch_valid_lawful_basis",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateintakebatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "consent_status__in",
                        ["unknown", "not_required", "granted", "withdrawn"],
                    )
                ),
                name="candidate_intake_batch_valid_consent",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateintakebatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "contact_permission__in",
                        ["unknown", "permitted", "restricted", "withdrawn"],
                    )
                ),
                name="candidate_intake_batch_valid_contact",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateintakebatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", True), ("status", "open")),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("status__in", ["completed", "discarded"]),
                    ),
                    _connector="OR",
                ),
                name="candidate_intake_batch_completion_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="candidateintakeitem",
            index=models.Index(
                fields=["batch", "status"], name="cand_intake_item_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateintakeitem",
            index=models.Index(fields=["sha256"], name="candidate_intake_sha256_idx"),
        ),
        migrations.AddConstraint(
            model_name="candidateintakeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "created", "skipped"])),
                name="candidate_intake_item_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateintakeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("candidate__isnull", True),
                        ("processed_at__isnull", True),
                        ("status", "pending"),
                    ),
                    models.Q(("processed_at__isnull", False), ("status", "created")),
                    models.Q(
                        ("candidate__isnull", True),
                        ("processed_at__isnull", False),
                        ("status", "skipped"),
                    ),
                    _connector="OR",
                ),
                name="candidate_intake_item_processing_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateintakeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "pending"),
                        models.Q(("original_filename", ""), _negated=True),
                        models.Q(("file", ""), _negated=True),
                        models.Q(("sha256", ""), _negated=True),
                        models.Q(("extracted_text", ""), _negated=True),
                    ),
                    models.Q(
                        ("content_type", ""),
                        ("extracted_text", ""),
                        ("file", ""),
                        ("original_filename", ""),
                        ("proposed_email", ""),
                        ("proposed_full_name", ""),
                        ("proposed_location", ""),
                        ("proposed_phone", ""),
                        ("proposed_source_reference", ""),
                        ("sha256", ""),
                        ("size_bytes__isnull", True),
                        ("status__in", ["created", "skipped"]),
                    ),
                    _connector="OR",
                ),
                name="candidate_intake_item_payload_consistent",
            ),
        ),
    ]
