# Generated by Django 5.2.17 on 2026-08-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0006_candidateintakebatch_candidateintakeitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateintakeitem",
            name="accepted_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intake_item",
                to="candidates.candidatedocument",
            ),
        ),
    ]
