# Generated by Django 5.2.17 on 2026-09-22 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0007_intake_accepted_document"),
        ("vacancies", "0002_vacancy_deletion_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateintakebatch",
            name="vacancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_intake_batches",
                to="vacancies.vacancy",
            ),
        ),
        migrations.CreateModel(
            name="CandidateVacancyConsideration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_scope",
                    models.CharField(
                        choices=[("current_vacancy", "This vacancy only")],
                        default="current_vacancy",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_considerations",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_candidate_vacancy_considerations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancy_considerations",
                        to="candidates.candidatedocument",
                    ),
                ),
                (
                    "intake_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_considerations",
                        to="candidates.candidateintakebatch",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_consideration",
                        to="candidates.candidatesource",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_considerations",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("contact_scope", "current_vacancy")),
                        name="candidate_vacancy_contact_scope_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("intake_batch__isnull", False)),
                        fields=("candidate", "vacancy", "intake_batch"),
                        name="unique_candidate_vacancy_intake_consideration",
                    ),
                ],
            },
        ),
    ]
