# Generated by Django 5.2.17 on 2026-09-24 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0008_candidateintakebatch_vacancy_and_more"),
        ("vacancies", "0003_vacancyrequirements_source_provenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatevacancyconsideration",
            name="origin",
            field=models.CharField(
                choices=[
                    ("application", "Vacancy application"),
                    ("candidate_pool", "Added from candidate pool"),
                ],
                default="application",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="candidatevacancyconsideration",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancy_considerations",
                to="candidates.candidatesource",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatevacancyconsideration",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin__in", ["application", "candidate_pool"])),
                name="candidate_vacancy_origin_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatevacancyconsideration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin", "candidate_pool")),
                fields=("candidate", "vacancy"),
                name="unique_candidate_vacancy_pool_reuse",
            ),
        ),
    ]
