"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from config.environment import env_bool, env_choice, env_int, env_list, secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ENVIRONMENT = env_choice(
    "DJANGO_ENVIRONMENT",
    default="development",
    choices={"development", "test", "production"},
)
IS_PRODUCTION = ENVIRONMENT == "production"

# Production cannot inherit development-friendly defaults.
SECRET_KEY = secret_key(production=IS_PRODUCTION)
DEBUG = env_bool("DJANGO_DEBUG", default=not IS_PRODUCTION)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured(
        "DJANGO_DEBUG must be false when DJANGO_ENVIRONMENT=production."
    )

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=() if IS_PRODUCTION else ("localhost", "127.0.0.1"),
)
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS is required when DJANGO_ENVIRONMENT=production."
    )
if IS_PRODUCTION and "*" in ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS must contain explicit hosts in production."
    )

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")
if IS_PRODUCTION and any(
    not origin.startswith("https://") for origin in CSRF_TRUSTED_ORIGINS
):
    raise ImproperlyConfigured(
        "DJANGO_CSRF_TRUSTED_ORIGINS must use https:// in production."
    )

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=IS_PRODUCTION)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=IS_PRODUCTION)
if IS_PRODUCTION and not all(
    (SECURE_SSL_REDIRECT, SESSION_COOKIE_SECURE, CSRF_COOKIE_SECURE)
):
    raise ImproperlyConfigured(
        "HTTPS redirect and secure session/CSRF cookies are required in production."
    )

# HSTS is intentionally opt-in because enabling it before HTTPS is stable can
# make a deployment unreachable. The production deployment check documents it.
SECURE_HSTS_SECONDS = env_int("DJANGO_SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)

# Trust this header only when a known reverse proxy overwrites it.
if env_bool("DJANGO_TRUST_X_FORWARDED_PROTO", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    "accounts",
    "audit",
    "candidates",
    "matching",
    "organizations",
    "outreach",
    "vacancies",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Candidate documents are private application data. No URL route serves this
# directory; controlled delivery is introduced in PROD-001.
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "organizations:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"


# Python AI Toolkit configuration. A real key is required only when the lazy
# application gateway makes an AI request; startup, checks, migrations, and
# ordinary tests remain provider-free. File logging stays disabled so the app
# controls all persistence of safe AI metadata.
AI_PROVIDER = os.getenv("AI_PROVIDER", "openai").strip().lower()
AI_PROVIDER_ENV_PREFIX = AI_PROVIDER.upper().replace("-", "_")
AI_TOOLKIT = {
    "provider": AI_PROVIDER,
    "api_key": os.getenv(f"{AI_PROVIDER_ENV_PREFIX}_API_KEY")
    or os.getenv("AI_API_KEY", ""),
    "model": os.getenv(f"{AI_PROVIDER_ENV_PREFIX}_MODEL")
    or os.getenv("AI_MODEL", "gpt-5.4-mini"),
    "embedding_model": os.getenv(f"{AI_PROVIDER_ENV_PREFIX}_EMBEDDING_MODEL")
    or os.getenv("AI_EMBEDDING_MODEL", "text-embedding-3-small"),
    "max_retries": env_int("AI_MAX_RETRIES", default=1),
    "file_logging_enabled": False,
}
AI_GATEWAY_FACTORY = os.getenv(
    "AI_GATEWAY_FACTORY", "ai_gateway.toolkit.ToolkitAIGateway"
).strip()
