# Generated by Django 5.2.17 on 2026-08-12 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_clientcompany"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow",
                    models.CharField(
                        choices=[
                            ("vacancy_requirements", "Vacancy requirements"),
                            ("candidate_profile", "Candidate profile"),
                            ("match_assessment", "Match assessment"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("vacancy_requirements", "Vacancy requirements"),
                            ("candidate_document", "Candidate document"),
                            ("candidate_profile", "Candidate profile"),
                            ("shortlist_entry", "Shortlist entry"),
                            ("match_assessment", "Match assessment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
                (
                    "result_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vacancy_requirements", "Vacancy requirements"),
                            ("candidate_document", "Candidate document"),
                            ("candidate_profile", "Candidate profile"),
                            ("shortlist_entry", "Shortlist entry"),
                            ("match_assessment", "Match assessment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("result_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "schema_version",
                    models.CharField(default="ai_usage_event.v1", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider_request_id", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(blank=True, max_length=255)),
                (
                    "duration_ms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=16,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("retries_used", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "output_tokens",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("total_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=18,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "failure_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gateway", "Gateway"),
                            ("application", "Application validation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_usage_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["organization", "workflow", "started_at"],
                        name="ai_usage_org_flow_started_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="ai_usage_target_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", True), ("status", "pending")
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                ("status__in", ["succeeded", "failed"]),
                            ),
                            _connector="OR",
                        ),
                        name="ai_usage_completion_matches_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "failed"),
                                models.Q(("failure_stage", ""), _negated=True),
                                models.Q(("failure_code", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("status", "failed"), _negated=True),
                                ("failure_code", ""),
                                ("failure_stage", ""),
                            ),
                            _connector="OR",
                        ),
                        name="ai_usage_failure_fields_match_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "succeeded"),
                                models.Q(("provider_request_id", ""), _negated=True),
                                models.Q(("model", ""), _negated=True),
                                models.Q(("result_type", ""), _negated=True),
                                ("result_id__isnull", False),
                            ),
                            models.Q(("status", "succeeded"), _negated=True),
                            _connector="OR",
                        ),
                        name="ai_usage_success_has_result_metadata",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("result_id__isnull", True), ("result_type", "")),
                            models.Q(
                                models.Q(("result_type", ""), _negated=True),
                                ("result_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ai_usage_result_reference_complete",
                    ),
                ],
            },
        ),
    ]
