# Generated by Django 5.2.17 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("audit", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="aiusageevent",
            name="result_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vacancy_requirements", "Vacancy requirements"),
                    ("candidate_document", "Candidate document"),
                    ("candidate_profile", "Candidate profile"),
                    ("shortlist_entry", "Shortlist entry"),
                    ("match_assessment", "Match assessment"),
                    ("review_decision", "Review decision"),
                    ("outreach_draft", "Outreach draft"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="aiusageevent",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("vacancy_requirements", "Vacancy requirements"),
                    ("candidate_document", "Candidate document"),
                    ("candidate_profile", "Candidate profile"),
                    ("shortlist_entry", "Shortlist entry"),
                    ("match_assessment", "Match assessment"),
                    ("review_decision", "Review decision"),
                    ("outreach_draft", "Outreach draft"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="aiusageevent",
            name="workflow",
            field=models.CharField(
                choices=[
                    ("vacancy_requirements", "Vacancy requirements"),
                    ("candidate_profile", "Candidate profile"),
                    ("match_assessment", "Match assessment"),
                    ("outreach_draft", "Outreach draft"),
                ],
                max_length=40,
            ),
        ),
    ]
