# Generated by Django 5.2.17 on 2026-08-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_outreach_usage_choices"),
        ("organizations", "0002_clientcompany"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                "candidate_deletion_requested",
                                "Candidate deletion requested",
                            ),
                            (
                                "candidate_retention_flagged",
                                "Candidate retention expired",
                            ),
                            (
                                "candidate_deletion_cancelled",
                                "Candidate deletion cancelled",
                            ),
                            ("candidate_deleted", "Candidate deleted"),
                            (
                                "candidate_document_downloaded",
                                "Candidate document downloaded",
                            ),
                            ("vacancy_deleted", "Vacancy deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("candidate_document", "Candidate document"),
                            ("vacancy", "Vacancy"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "schema_version",
                    models.CharField(default="audit_event.v1", max_length=50),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["organization", "occurred_at"],
                        name="audit_event_org_time_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_event_object_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                [
                                    "candidate_deletion_requested",
                                    "candidate_retention_flagged",
                                    "candidate_deletion_cancelled",
                                    "candidate_deleted",
                                    "candidate_document_downloaded",
                                    "vacancy_deleted",
                                ],
                            )
                        ),
                        name="audit_event_has_valid_action",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "object_type__in",
                                ["candidate", "candidate_document", "vacancy"],
                            )
                        ),
                        name="audit_event_has_valid_object_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "action__in",
                                    [
                                        "candidate_deletion_requested",
                                        "candidate_retention_flagged",
                                        "candidate_deletion_cancelled",
                                        "candidate_deleted",
                                    ],
                                ),
                                ("object_type", "candidate"),
                            ),
                            models.Q(
                                ("action", "candidate_document_downloaded"),
                                ("object_type", "candidate_document"),
                            ),
                            models.Q(
                                ("action", "vacancy_deleted"),
                                ("object_type", "vacancy"),
                            ),
                            _connector="OR",
                        ),
                        name="audit_event_action_matches_object",
                    ),
                ],
            },
        ),
    ]
