# Generated by Django 5.2.17 on 2026-08-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_auditevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id_snapshot",
                    models.PositiveBigIntegerField(unique=True),
                ),
                ("policy_version", models.PositiveIntegerField()),
                ("deletion_requested_at", models.DateTimeField()),
                ("purged_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-purged_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="DataLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id_snapshot", models.PositiveBigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("temporary_intake_purged", "Intake purged"),
                            ("completed_job_purged", "Job purged"),
                            ("match_run_purged", "Match run purged"),
                            ("outreach_chain_purged", "Outreach chain purged"),
                            ("metadata_purged", "Metadata purged"),
                            (
                                "organization_deletion_requested",
                                "Organization deletion requested",
                            ),
                            (
                                "organization_deletion_cancelled",
                                "Organization deletion cancelled",
                            ),
                            ("organization_purged", "Organization purged"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("intake_item", "Intake item"),
                            ("background_job", "Background job"),
                            ("match_run", "Match run"),
                            ("shortlist_entry", "Shortlist entry"),
                            ("metadata_group", "Metadata group"),
                            ("organization", "Organization"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("policy_version", models.PositiveIntegerField()),
                (
                    "schema_version",
                    models.CharField(default="data_lifecycle_event.v1", max_length=50),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_lifecycle_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["organization_id_snapshot", "occurred_at"],
                        name="lifecycle_event_org_time_idx",
                    )
                ],
            },
        ),
    ]
