# Generated by Django 5.2.17 on 2026-08-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_organizationtombstone_datalifecycleevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantManagementEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id_snapshot", models.PositiveBigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("organization_created", "Organization created"),
                            ("membership_created", "Membership created"),
                            ("membership_activated", "Membership activated"),
                            ("membership_deactivated", "Membership deactivated"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "subject_user_id_snapshot",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "membership_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not applicable"),
                            ("admin", "Administrator"),
                            ("recruiter", "Recruiter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="tenant_management_event.v1",
                        max_length=50,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_management_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["organization_id_snapshot", "occurred_at"],
                        name="tenant_event_org_time_idx",
                    )
                ],
            },
        )
    ]
