# Generated by Django 5.2.17 on 2026-08-29 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0005_tenantmanagementevent"),
        (
            "organizations",
            "0003_organizationretentionpolicy_retentionexception_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_event_has_valid_action",
        ),
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_event_has_valid_object_type",
        ),
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_event_action_matches_object",
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("candidate_deletion_requested", "Candidate deletion requested"),
                    ("candidate_retention_flagged", "Candidate retention expired"),
                    ("candidate_deletion_cancelled", "Candidate deletion cancelled"),
                    ("candidate_deleted", "Candidate deleted"),
                    ("candidate_document_downloaded", "Candidate document downloaded"),
                    ("candidate_updated", "Candidate updated"),
                    ("candidate_source_updated", "Candidate source updated"),
                    ("candidate_profile_corrected", "Candidate profile corrected"),
                    ("vacancy_deleted", "Vacancy deleted"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate"),
                    ("candidate_source", "Candidate source"),
                    ("candidate_profile", "Candidate profile"),
                    ("candidate_document", "Candidate document"),
                    ("vacancy", "Vacancy"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        [
                            "candidate_deletion_requested",
                            "candidate_retention_flagged",
                            "candidate_deletion_cancelled",
                            "candidate_deleted",
                            "candidate_document_downloaded",
                            "candidate_updated",
                            "candidate_source_updated",
                            "candidate_profile_corrected",
                            "vacancy_deleted",
                        ],
                    )
                ),
                name="audit_event_has_valid_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "object_type__in",
                        [
                            "candidate",
                            "candidate_source",
                            "candidate_profile",
                            "candidate_document",
                            "vacancy",
                        ],
                    )
                ),
                name="audit_event_has_valid_object_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "action__in",
                            [
                                "candidate_deletion_requested",
                                "candidate_retention_flagged",
                                "candidate_deletion_cancelled",
                                "candidate_deleted",
                                "candidate_updated",
                            ],
                        ),
                        ("object_type", "candidate"),
                    ),
                    models.Q(
                        ("action", "candidate_source_updated"),
                        ("object_type", "candidate_source"),
                    ),
                    models.Q(
                        ("action", "candidate_profile_corrected"),
                        ("object_type", "candidate_profile"),
                    ),
                    models.Q(
                        ("action", "candidate_document_downloaded"),
                        ("object_type", "candidate_document"),
                    ),
                    models.Q(("action", "vacancy_deleted"), ("object_type", "vacancy")),
                    _connector="OR",
                ),
                name="audit_event_action_matches_object",
            ),
        ),
    ]
