# Generated by Django 5.2.17 on 2026-08-10 18:13

import re
import unicodedata
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_requirement_skills(apps, schema_editor):
    Skill = apps.get_model("matching", "Skill")
    RequirementSkill = apps.get_model("matching", "RequirementSkill")
    VacancyRequirements = apps.get_model("vacancies", "VacancyRequirements")
    whitespace_re = re.compile(r"\s+")

    for requirements in VacancyRequirements.objects.select_related(
        "vacancy"
    ).iterator():
        seen = set()
        groups = (
            ("must_have", requirements.must_have_skills),
            ("nice_to_have", requirements.nice_to_have_skills),
        )
        for importance, labels in groups:
            position = 0
            for raw_label in labels:
                display_name = whitespace_re.sub(
                    " ", unicodedata.normalize("NFKC", raw_label).strip()
                )
                normalized_name = display_name.casefold()
                if (
                    not normalized_name
                    or len(normalized_name) > 120
                    or normalized_name in seen
                ):
                    continue
                seen.add(normalized_name)
                position += 1
                skill, _ = Skill.objects.get_or_create(
                    organization_id=requirements.vacancy.organization_id,
                    normalized_name=normalized_name,
                    defaults={"name": display_name},
                )
                RequirementSkill.objects.create(
                    requirements=requirements,
                    skill=skill,
                    importance=importance,
                    source_label=display_name,
                    position=position,
                )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidates", "0003_candidatedocument_extraction"),
        ("organizations", "0002_clientcompany"),
        ("vacancies", "0002_vacancy_deletion_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("normalized_name", models.CharField(editable=False, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="RequirementSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("must_have", "Must have"),
                            ("nice_to_have", "Nice to have"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_label", models.CharField(max_length=120)),
                ("position", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requirements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_records",
                        to="vacancies.vacancyrequirements",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirement_records",
                        to="matching.skill",
                    ),
                ),
            ],
            options={
                "ordering": ("importance", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="HardConstraintRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("required_skill", "Required skill"),
                            ("minimum_experience", "Minimum years of experience"),
                            ("location", "Location"),
                            ("work_mode", "Work mode"),
                            ("language", "Language"),
                            ("education", "Education"),
                            ("certification", "Certification"),
                            ("employment_type", "Employment type"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("has_skill", "Has skill"),
                            ("at_least", "At least"),
                            ("equals", "Equals"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_text", models.TextField()),
                ("expected_value", models.CharField(blank=True, max_length=200)),
                (
                    "normalized_expected_value",
                    models.CharField(blank=True, editable=False, max_length=200),
                ),
                (
                    "numeric_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "unknown_outcome",
                    models.CharField(
                        choices=[("keep_for_review", "Keep for recruiter review")],
                        default="keep_for_review",
                        editable=False,
                        max_length=30,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hard_constraint_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_constraint_rules",
                        to="vacancies.vacancyrequirements",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hard_constraint_rules",
                        to="matching.skill",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="CandidateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_label", models.CharField(max_length=120)),
                ("evidence", models.TextField(blank=True)),
                (
                    "years_experience",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_records",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_candidate_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_records",
                        to="candidates.candidatedocument",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_records",
                        to="matching.skill",
                    ),
                ),
            ],
            options={
                "ordering": ("skill__name", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("organization", "normalized_name"),
                name="unique_normalized_skill_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementskill",
            constraint=models.UniqueConstraint(
                fields=("requirements", "skill"),
                name="unique_skill_per_requirements_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementskill",
            constraint=models.UniqueConstraint(
                fields=("requirements", "importance", "position"),
                name="unique_skill_position_per_requirement_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementskill",
            constraint=models.CheckConstraint(
                condition=models.Q(("importance__in", ["must_have", "nice_to_have"])),
                name="requirement_skill_has_valid_importance",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementskill",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="requirement_skill_position_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="hardconstraintrule",
            constraint=models.UniqueConstraint(
                fields=("requirements", "position"),
                name="unique_hard_constraint_position_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="hardconstraintrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="hard_constraint_position_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="hardconstraintrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rule_type__in",
                        [
                            "required_skill",
                            "minimum_experience",
                            "location",
                            "work_mode",
                            "language",
                            "education",
                            "certification",
                            "employment_type",
                        ],
                    )
                ),
                name="hard_constraint_has_valid_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="hardconstraintrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operator__in", ["has_skill", "at_least", "equals"])
                ),
                name="hard_constraint_has_valid_operator",
            ),
        ),
        migrations.AddConstraint(
            model_name="hardconstraintrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("unknown_outcome", "keep_for_review")),
                name="hard_constraint_unknown_keeps_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="hardconstraintrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expected_value", ""),
                        ("normalized_expected_value", ""),
                        ("numeric_value__isnull", True),
                        ("operator", "has_skill"),
                        ("rule_type", "required_skill"),
                        ("skill__isnull", False),
                    ),
                    models.Q(
                        ("expected_value", ""),
                        ("normalized_expected_value", ""),
                        ("numeric_value__isnull", False),
                        ("operator", "at_least"),
                        ("rule_type", "minimum_experience"),
                        ("skill__isnull", True),
                    ),
                    models.Q(
                        ("numeric_value__isnull", True),
                        ("operator", "equals"),
                        (
                            "rule_type__in",
                            [
                                "location",
                                "work_mode",
                                "language",
                                "education",
                                "certification",
                                "employment_type",
                            ],
                        ),
                        ("skill__isnull", True),
                        models.Q(("expected_value", ""), _negated=True),
                        models.Q(("normalized_expected_value", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="hard_constraint_payload_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="hardconstraintrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("numeric_value__isnull", True),
                    ("numeric_value__gte", 0),
                    _connector="OR",
                ),
                name="hard_constraint_numeric_is_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateskill",
            constraint=models.UniqueConstraint(
                fields=("candidate", "skill"), name="unique_skill_per_candidate"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateskill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("years_experience__isnull", True),
                    ("years_experience__gte", 0),
                    _connector="OR",
                ),
                name="candidate_skill_years_is_nonnegative",
            ),
        ),
        migrations.RunPython(backfill_requirement_skills, migrations.RunPython.noop),
    ]
