# Generated by Django 5.2.17 on 2026-08-11 06:51

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_candidatedocument_extraction"),
        ("matching", "0001_initial"),
        ("vacancies", "0002_vacancy_deletion_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=50)),
                ("shortlist_limit", models.PositiveIntegerField()),
                ("evaluated_count", models.PositiveIntegerField()),
                ("eligible_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_match_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_runs",
                        to="vacancies.vacancyrequirements",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ShortlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "filter_outcome",
                    models.CharField(
                        choices=[("passed", "Passed"), ("review", "Needs review")],
                        max_length=20,
                    ),
                ),
                ("matched_must_have", models.PositiveIntegerField(default=0)),
                ("total_must_have", models.PositiveIntegerField(default=0)),
                ("matched_nice_to_have", models.PositiveIntegerField(default=0)),
                ("total_nice_to_have", models.PositiveIntegerField(default=0)),
                ("score_breakdown", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortlist_entries",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "match_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="matching.matchrun",
                    ),
                ),
            ],
            options={
                "ordering": ("rank", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="matchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("shortlist_limit__gte", 1)),
                name="match_run_limit_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible_count__lte", models.F("evaluated_count"))
                ),
                name="match_run_eligible_not_above_evaluated",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortlistentry",
            constraint=models.UniqueConstraint(
                fields=("match_run", "candidate"), name="unique_candidate_per_match_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="shortlistentry",
            constraint=models.UniqueConstraint(
                fields=("match_run", "rank"), name="unique_rank_per_match_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="shortlistentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("rank__gte", 1)),
                name="shortlist_entry_rank_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortlistentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                name="shortlist_entry_score_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortlistentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("filter_outcome__in", ["passed", "review"])),
                name="shortlist_entry_has_eligible_filter_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortlistentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("matched_must_have__lte", models.F("total_must_have"))
                ),
                name="shortlist_must_match_not_above_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortlistentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("matched_nice_to_have__lte", models.F("total_nice_to_have"))
                ),
                name="shortlist_nice_match_not_above_total",
            ),
        ),
    ]
