# Generated by Django 5.2.17 on 2026-08-11 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0002_matchrun_shortlistentry_and_more"),
        ("vacancies", "0002_vacancy_deletion_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="matchrun",
            name="shortlisted_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="matchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("shortlisted_count__lte", models.F("eligible_count"))
                ),
                name="match_run_shortlisted_not_above_eligible",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("shortlisted_count__lte", models.F("shortlist_limit"))
                ),
                name="match_run_shortlisted_not_above_limit",
            ),
        ),
    ]
