# Generated by Django 5.2.17 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0003_matchrun_shortlisted_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchrun",
            name="candidate_input_signature",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="matchrun",
            name="input_snapshot_version",
            field=models.CharField(
                default="deterministic_match_inputs.v1",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="matchrun",
            name="requirements_input_signature",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
