# Generated by Django 5.2.17 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0004_candidateprofile"),
        ("matching", "0004_matchrun_input_signatures"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateskill",
            name="source_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_skill_records",
                to="candidates.candidateprofile",
            ),
        ),
    ]
