# Generated by Django 5.2.17 on 2026-08-12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0004_candidateprofile"),
        ("matching", "0005_candidateskill_source_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "schema_version",
                    models.CharField(default="match_assessment.v1", max_length=50),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "traffic_light",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("amber", "Amber"),
                            ("green", "Green"),
                        ],
                        max_length=10,
                    ),
                ),
                ("summary", models.TextField()),
                ("matching_requirements", models.JSONField(blank=True, default=list)),
                ("gaps", models.JSONField(blank=True, default=list)),
                ("uncertainties", models.JSONField(blank=True, default=list)),
                ("review_recommendation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_assessments",
                        to="candidates.candidateprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_match_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_assessments",
                        to="vacancies.vacancyrequirements",
                    ),
                ),
                (
                    "shortlist_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="matching.shortlistentry",
                    ),
                ),
            ],
            options={
                "ordering": ("-version", "-created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shortlist_entry", "version"),
                        name="unique_assessment_version_per_shortlist_entry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="match_assessment_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                        name="match_assessment_score_in_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("traffic_light__in", ["red", "amber", "green"])
                        ),
                        name="match_assessment_valid_traffic_light",
                    ),
                ],
            },
        ),
    ]
