# Generated by Django 5.2.17 on 2026-08-13 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0006_matchassessment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approve"),
                            ("rejected", "Reject"),
                            ("revisit", "Revisit later"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(2000)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_decisions",
                        to="matching.matchassessment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_review_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shortlist_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_decisions",
                        to="matching.shortlistentry",
                    ),
                ),
            ],
            options={
                "ordering": ("-version", "-created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shortlist_entry", "version"),
                        name="unique_review_decision_version_per_entry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="review_decision_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("decision__in", ["approved", "rejected", "revisit"])
                        ),
                        name="review_decision_valid_choice",
                    ),
                ],
            },
        ),
    ]
