# Generated by Django 5.2.17 on 2026-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_reviewdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistentry',
            name='discovery_signals',
            field=models.JSONField(default=list),
        ),
    ]
