# Generated by Django 5.2.17 on 2026-08-15 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_clientcompany"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow",
                    models.CharField(
                        choices=[
                            ("candidate_profile_batch", "Candidate profile extraction"),
                            (
                                "shortlist_assessment_batch",
                                "Whole-shortlist assessment",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("match_run", "Match run"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_id", models.PositiveBigIntegerField()),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("completed_with_errors", "Completed with exceptions"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("succeeded_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "schema_version",
                    models.CharField(default="background_job.v1", max_length=50),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_background_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_jobs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="BackgroundTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("candidate_document", "Candidate document"),
                            ("shortlist_entry", "Shortlist entry"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("skipped", "Needs attention"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "result_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("candidate_profile", "Candidate profile"),
                            ("match_assessment", "Match assessment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("result_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[("created", "Created"), ("reused", "Reused")],
                        max_length=20,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=50)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="operations.backgroundjob",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["organization", "status"], name="background_job_org_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "workflow__in",
                        ["candidate_profile_batch", "shortlist_assessment_batch"],
                    )
                ),
                name="background_job_valid_workflow",
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_type__in", ["organization", "match_run"])),
                name="background_job_valid_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["queued", "running", "succeeded", "completed_with_errors"],
                    )
                ),
                name="background_job_valid_status",
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundtask",
            index=models.Index(
                fields=["status", "lease_expires_at", "id"],
                name="background_task_claim_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundtask",
            constraint=models.UniqueConstraint(
                fields=("job", "target_type", "target_id"),
                name="unique_background_target_per_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_type__in", ["candidate_document", "shortlist_entry"])
                ),
                name="background_task_valid_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["queued", "running", "succeeded", "skipped", "failed"],
                    )
                ),
                name="background_task_valid_status",
            ),
        ),
    ]
