# Generated by Django 5.2.17 on 2026-08-10 14:59

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import vacancies.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_clientcompany"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancies",
                        to="organizations.clientcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vacancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="VacancyRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "schema_version",
                    models.CharField(default="vacancy_requirements.v1", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("confirmed", "Confirmed")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "creation_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("ai_assisted", "AI assisted"),
                            ("imported", "Imported"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("source_description", models.TextField()),
                ("summary", models.TextField(blank=True)),
                (
                    "must_have_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[vacancies.models.validate_string_list],
                    ),
                ),
                (
                    "nice_to_have_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[vacancies.models.validate_string_list],
                    ),
                ),
                (
                    "minimum_years_experience",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("location_requirement", models.CharField(blank=True, max_length=200)),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("on_site", "On site"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                            ("flexible", "Flexible"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "language_requirements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[vacancies.models.validate_string_list],
                    ),
                ),
                (
                    "education_requirements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[vacancies.models.validate_string_list],
                    ),
                ),
                (
                    "certification_requirements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[vacancies.models.validate_string_list],
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("full_time", "Full time"),
                            ("part_time", "Part time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("internship", "Internship"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "hard_constraints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[vacancies.models.validate_string_list],
                    ),
                ),
                (
                    "ambiguities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[vacancies.models.validate_string_list],
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_vacancy_requirement_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vacancy_requirement_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_versions",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "ordering": ("-version", "-created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["organization", "status"], name="vacancy_org_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "open", "paused", "closed"])
                ),
                name="vacancy_has_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyrequirements",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "version"),
                name="unique_requirement_version_per_vacancy",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyrequirements",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="vacancy_requirement_version_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyrequirements",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "confirmed"])),
                name="vacancy_requirement_has_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyrequirements",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("creation_method__in", ["manual", "ai_assisted", "imported"])
                ),
                name="vacancy_requirement_has_valid_creation_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyrequirements",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "employment_type__in",
                        [
                            "unknown",
                            "full_time",
                            "part_time",
                            "contract",
                            "temporary",
                            "internship",
                            "other",
                        ],
                    )
                ),
                name="vacancy_requirement_has_valid_employment_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyrequirements",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "work_mode__in",
                        ["unknown", "on_site", "hybrid", "remote", "flexible"],
                    )
                ),
                name="vacancy_requirement_has_valid_work_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyrequirements",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confirmed_at__isnull", True),
                        ("confirmed_by__isnull", True),
                        ("status", "draft"),
                    ),
                    models.Q(
                        ("confirmed_at__isnull", False),
                        ("confirmed_by__isnull", False),
                        ("status", "confirmed"),
                    ),
                    _connector="OR",
                ),
                name="vacancy_requirement_confirmation_is_consistent",
            ),
        ),
    ]
